# site properties and page defaults
title: Mandeville Lab
subtitle: "Fish are so weird"
description: We study the evolutionary genetics and ecology of freshwater fishes, plus a few more things, at Northern Michigan University
header: images/harlow.jpg
footer: images/harlow.jpg
proofer: false

# site social media and other links
links:
  email: lmandevi@nmu.edu
  orcid: 0000-0002-9461-9140
  google-scholar: https://scholar.google.com/citations?user=k2OAOOIAAAAJ&hl=en
  #github: your-lab
  #twitter: YourLabHandle
  #youtube: YourLabChannel

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
